import "./index.scss";
import "./js/pages/notifications";
import "./js/pages/settings";
import "./js/pages/home-page";
import "./js/pages/passes-page";
import "./js/pages/requests-page";
import "./js/pages/making-request-page";
import "./js/pages/settings-about";
import "./js/pages/applications";
import "./js/pages/adding_application";
import "./js/pages/outgoing-requests";
import "./js/pages/incoming-requests";
import "./js/pages/incoming-request-details";
import "./js/pages/request-repeat";
import "./js/pages/login-page";
import "./js/pages/news";
import "./js/pages/add-news";
import "./js/components/header";
import './js/components/modal'
import './js/components/modal-change-work'
import './js/components/modal-pass'
import './js/components/modal-share-pass'
import './js/components/modal-success'
import './js/components/modal-sms'
import "./js/components/switcher";
import "./js/components/form";
import "./js/components/modal-reject-request";
import "./js/components/input-add-file";
import "./js/components/modal-exit";
import "./js/components/filters";
import "./js/components/modal-change-application";